[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/.cache/Cypress"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = ["node_modules/.cache"]